'use strict';
const fs = require('fs');
const path = require('path');
const axios = require('axios');
const chalk = require('chalk');
const { spawn } = require('child_process');
const { loadConfig, findGitRoot, WEBHOOK_URL } = require('./config');

function extractTicketId(branchName) {
  const match = branchName.match(/([A-Z][A-Z0-9]+-\d+)/i);
  return match ? match[1].toUpperCase() : null;
}

async function checkout(branchName) {
  const config = loadConfig();

  if (!config) {
    console.log(chalk.yellow('\n⚠️  Not configured. Run: lem-ai setup\n'));
    return;
  }

  // ────────────────────────────────────────────────────────────
  // PHASE 1: Main Process — Spawn Background Worker & Exit
  // ────────────────────────────────────────────────────────────
  if (!process.env.LEMAI_BG) {
    console.log(chalk.cyan(`\n[lem-ai] 🚀 Branch detected: ${chalk.bold(branchName)}`));
    console.log(chalk.gray(`[lem-ai] ⚡ Generating Implementation.md in background...`));
    console.log(chalk.gray(`[lem-ai] 🏁 Git checkout will proceed instantly.\n`));

    const gitRoot = findGitRoot(process.cwd()) || process.cwd();
    const logPath = path.join(gitRoot, '.lem-ai.log');

    // Open log file for background process
    const out = fs.openSync(logPath, 'a');
    const err = fs.openSync(logPath, 'a');

    // Spawn this same CLI command but with LEMAI_BG=true
    const child = spawn(process.argv[0], [process.argv[1], 'checkout', branchName], {
      detached: true,
      stdio: ['ignore', out, err],
      env: { ...process.env, LEMAI_BG: 'true' },
      cwd: process.cwd()
    });

    child.unref();
    process.exit(0);
  }

  // ────────────────────────────────────────────────────────────
  // PHASE 2: Background Process — Do the heavy lifting
  // ────────────────────────────────────────────────────────────
  const ticketId = extractTicketId(branchName);
  const startTime = new Date().toISOString();

  const gitRoot = findGitRoot(process.cwd()) || process.cwd();
  const logPath = path.join(gitRoot, '.lem-ai.log');

  const log = (msg) => {
    fs.appendFileSync(logPath, `[${new Date().toISOString()}] ${msg}\n`);
  };

  log(`Starting background sync for ${branchName}...`);

  const headers = { 'Content-Type': 'application/json' };
  if (config.secret) headers['Authorization'] = `Bearer ${config.secret}`;
  if (config.apiKey) headers['x-sdk-key'] = config.apiKey;

  // Fire and Forget: Start the request without blocking the main flow
  axios.post(
    WEBHOOK_URL,
    { branchName, ticketId, timestamp: startTime },
    { headers, timeout: 300000 }
  ).then(response => {
    const { markdown } = response.data;

    if (markdown) {
      const outputPath = path.join(gitRoot, config.outputFile || 'Implementation.md');
      fs.writeFileSync(outputPath, markdown, 'utf-8');
      log(`✅ Implementation.md generated successfully.`);
    } else {
      log(`ℹ️ No markdown generated by backend.`);
    }
    process.exit(0);
  }).catch(err => {
    log(`❌ Error: ${err.message}`);
    if (err.response) {
      log(`Backend error ${err.response.status}: ${JSON.stringify(err.response.data)}`);
    }
    process.exit(1);
  });
}

module.exports = { checkout };
